name = "jie4ma-server"
main = "worker.js"
compatibility_date = "2024-11-01"
workers_dev = true

[vars]
PROVIDER = "deepseek"
DEEPSEEK_MODEL = "deepseek-chat"
OPENAI_MODEL = "gpt-4o-mini"
ARK_ENDPOINT = ""
ARK_MODEL = "doubao-seed-1-6-lite-251015"
